[Improvement] improved script, added new option -n and added new variables to global.conf
Signed-off-by: Adán Samuel Marín Jacquot <adan.marin@zevenet.com>

	modificado:     usr/local/zevenet/bin/checkupgrades
	modificado:     usr/local/zevenet/share/global.conf.template

diff --git a/usr/local/zevenet/bin/checkupgrades b/usr/local/zevenet/bin/checkupgrades
--- a/usr/local/zevenet/bin/checkupgrades
+++ b/usr/local/zevenet/bin/checkupgrades
@@ -1,43 +1,62 @@
 #!/bin/bash
 
-apt-get update &>/dev/null
+# load global.conf variables
+if [ -f "/usr/local/zevenet/bin/load_global_conf" ];
+then
+       	source /usr/local/zevenet/bin/load_global_conf
+        load_global_conf
+else
+	echo "I can't find environment variable"
+	exit 1
+fi
+
+# test connection with zevenet update system
+$aptget_bin update &>/dev/null
 if [ $? != 0 ]
 then
 	echo "Error connecting to Zevenet Update System, check connection to https://repo.zevenet.com"
 	exit 1
 fi
 
-if [ -z $1 ]
-then
-	packages=`apt list --upgradable 2>/dev/null | awk 'FNR > 1' | wc -l`
-	if [ $packages \> 0 ]
-	then
-		echo "$packages packages require upgrade"
-		echo "To upgrade, execute: apt-get upgrade"
-		echo "last check at `date` - $packages packages require upgrade, update this information with: checkupgrades" > /usr/local/zevenet/app/checkupgrades/share/message.txt
-		echo "To upgrade, execute: apt-get upgrade" >> /usr/local/zevenet/app/checkupgrades/share/message.txt
-		apt list --upgradable 2>/dev/null | cut -d"/" -f 1  | tr  '\n' ' ' > /usr/local/zevenet/app/checkupgrades/share/package_upgradables.txt
-	else
-		echo "Zevenet Packages are up-to-date."
-	fi
-else
-	package=$1
+# check if there are upgradable packages
+case "$1" in
+'')
+        packages=`$apt_bin list --upgradable 2>/dev/null | awk 'FNR > 1' | wc -l`
+        if [ $packages \> 0 ]
+       	then
+               	echo "$packages packages require upgrade"
+                echo "To upgrade, execute: apt-get upgrade"
+       	        echo "last check at `date` - $packages packages require upgrade, update this information with: checkupgrades" > /usr/local/zevenet/app/checkupgrades/share/message.txt
+               	echo "To upgrade, execute: apt-get upgrade" >> /usr/local/zevenet/app/checkupgrades/share/message.txt
+                $apt_bin list --upgradable 2>/dev/null | cut -d"/" -f 1  | tr  '\n' ' ' > /usr/local/zevenet/app/checkupgrades/share/package_upgradables.txt
+       	else
+               	echo "Zevenet Packages are up-to-date."
+                echo "Zevenet Packages are up-to-date." > /usr/local/zevenet/app/checkupgrades/share/message.txt
+       	fi
+;;
 
-	dpkg -l | grep $package > /dev/null
+'-n')
+	# Packages number not update
+	number=`$apt_bin list --upgradable 2>/dev/null | awk 'FNR > 1' | wc -l`
+	echo "$number"
+;;
+
+*)
+	$dpkg_bin -l | grep $1 > /dev/null
 	if [ $? = 0 ];
 	then
-		installed=`apt-cache policy $package | grep -i installed | cut -d ":" -f2 | sed 's/ //g'`
-		candidate=`apt-cache policy $package | grep -i candidate | cut -d ":" -f2 | sed 's/ //g'`
+		installed=`$aptcache_bin policy $1 | grep -i installed | cut -d ":" -f2 | sed 's/ //g'`
+		candidate=`$aptcache_bin policy $1 | grep -i candidate | cut -d ":" -f2 | sed 's/ //g'`
 		if [ "$installed" != "$candidate" ];
 		then
-			echo "There is a new version of $package"
-			echo "installed = $package $installed"
-			echo "candidate = $package $candidate"
+			echo "There is a new version of $1"
+			echo "installed = $1 $installed"
+			echo "candidate = $1 $candidate"
 		else
-			echo "$package is already the newest version $installed"
+			echo "$1 is already the newest version $installed"
 		fi
 	else
-		echo "$package it is not installed in the system"
+		echo "$1 it is not installed in the system"
 	fi
-fi
-
+;;
+esac
