[Improvement] Remove deprecated logfile messages in postinst process
Signed-off-by: Jose Pablo <josepgl@sofintel.net>

	modified:   DEBIAN/postinst
	modified:   DEBIAN/postinst_BM

diff --git a/DEBIAN/postinst_BM b/DEBIAN/postinst_BM
--- a/DEBIAN/postinst_BM
+++ b/DEBIAN/postinst_BM
@@ -1,11 +1,10 @@
 #!/bin/bash
 
-LOGFILE="/usr/local/zenloadbalancer/logs/zenloadbalancer.log"
 GLOBALCF="/usr/local/zenloadbalancer/config/global.conf"
 GLOBALCFT="/usr/local/zenloadbalancer/app/checkglobalconf/global.conf.tpl"
 
-[ ! "$1" == "configure" ] && echo "Installation aborted $1 $2" | tee -a $LOGFILE && exit 1
-[ "$1" == "configure" ] && echo "Completing the ZLB installation..." | tee -a $LOGFILE
+[ ! "$1" == "configure" ] && echo "Installation aborted $1 $2" && exit 1
+[ "$1" == "configure" ] && echo "Completing the ZLB installation..."
 
 if [ -f /usr/local/zenloadbalancer/app/zennetname/write_net_rules ]; then
 	cp -f /usr/local/zenloadbalancer/app/zennetname/write_net_rules /lib/udev/
