Control if install or upgrade is aborted Signed-off-by: Jose <root@dev32.(none)>
	modified:   DEBIAN/postinst

diff --git a/DEBIAN/postinst b/DEBIAN/postinst
--- a/DEBIAN/postinst
+++ b/DEBIAN/postinst
@@ -1,5 +1,6 @@
 #!/bin/bash
-echo "Los parámetros son $1 $2 $3"
+LOGFILE="/usr/local/zenloadbalancer/logs/zenloadbalancer.log"
+[ ! "$1" == "configure" ] && echo "Installation aborted $1 $2" | tee -a $LOGFILE; exit 1
 MSCRIPT="/usr/local/zenloadbalancer/app/zbin/zlbmigration302to303.pl"
 GLOBALCF="/usr/local/zenloadbalancer/config/global.conf"
 GLOBALCFT="/usr/local/zenloadbalancer/app/checkglobalconf/global.conf.tpl"
