[Improvement] Do not use CE repository to update CE. Create repository using only EE
Signed-off-by: Alvaro Cano <alvaro.cano@zevenet.com>

	modified:   build-pkg/config
	modified:   build-pkg/e2c
	new file:   build-pkg/files-ce/DEBIAN/control
	new file:   build-pkg/files-ce/DEBIAN/postinst
	new file:   build-pkg/files-ce/DEBIAN/preinst
	new file:   build-pkg/files-ce/README.md
	new file:   build-pkg/files-ce/build-pkg/.gitignore
	new file:   build-pkg/files-ce/build-pkg/gen_pkg.sh
	new file:   build-pkg/files-ce/build-pkg/packages/.gitignore
	new file:   build-pkg/files-ce/etc/motd.tail
	new file:   build-pkg/files-ce/etc/zevenet_version
	new file:   build-pkg/files-ce/usr/local/zevenet/share/global.conf.template
	new file:   build-pkg/files-ce/usr/local/zevenet/share/pound.cfg.template
	new file:   build-pkg/files-ce/usr/local/zevenet/www/zapi/v3.1/zapi.cgi
	new file:   build-pkg/files-ce/usr/local/zevenet/www/zapi/v4.0/zapi.cgi
	new file:   build-pkg/files-ce/zlb-debian-installer.sh

diff --git a/build-pkg/e2c b/build-pkg/e2c
--- a/build-pkg/e2c
+++ b/build-pkg/e2c
@@ -4,11 +4,16 @@
 # This script create a commit with the last EE changes in the merge-ee branch of the community repository.
 # The script uses the current content of the EE repository, it does not use the last commit.
 
+rsync_bin=`which rsync`
+
+if [[ -z "$rsync_bin" ]]; then
+	echo "ERROR: Please install rsync first. Thanks ;)"
+	exit 1;
+fi
 
 function msg() {
 	echo -e "\n#### ${1} ####\n"
 }
-
 
 
 function print_usage_and_exit() {
@@ -18,6 +23,7 @@ function print_usage_and_exit() {
 	--auto-merge		Apply automatly a commit in the CE branch 'merge-ee'"
 	exit 1
 }
+
 
 while [ $# -gt 0 ]; do
 	case $1 in
@@ -33,19 +39,45 @@ while [ $# -gt 0 ]; do
 	shift
 done
 
+# variables
 CE_REPO="git@gitlab.zevenet.com:cristina.guerra/zevenet-ce.git"
 CE_BRANCH="merge-ee"
 
 zevenet_home='usr/local/zevenet'
 BASE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
-com_dir=${BASE_DIR}/CE_WORKDIR
-ent_dir=${BASE_DIR}/EE_WORKDIR
-rsync_bin=`which rsync`
+com_dir="${BASE_DIR}/CE_WORKDIR"
+tmp_dir="${BASE_DIR}/TMP_CE_WORKDIR"
+ce_files_dir="${BASE_DIR}/files-ce"
 
-if [[ -z "$rsync_bin" ]]; then
-	echo "ERROR: Please install rsync first. Thanks ;)"
-	exit 1;
-fi
+# get commit hash
+EE_COMMIT=$(git log --oneline | head -1 | cut -d' ' -f1)
+
+# Setup a clean EE environment
+msg "Cleaning the EE directory..."
+rm -rf $tmp_dir
+mkdir $tmp_dir
+
+msg "Copying EE files..."
+$rsync_bin -a --exclude "/$(basename "$BASE_DIR")" ../* $tmp_dir/
+
+# load files
+source config
+
+# remove EE files
+msg "Removing EE files..."
+for file in "${encrypted_files[@]}"; do
+	rm -rf ${tmp_dir}/$file
+done
+for file in "${enterprise_files[@]}"; do
+	rm -rf ${tmp_dir}/$file
+done
+
+# copy community files
+msg "Copying CE files..."
+for file in "${community_files[@]}"; do
+	cp -r $ce_files_dir ${tmp_dir}
+done
+
 
 # clone CE repository
 msg "Cloning the community repository..."
@@ -56,51 +88,12 @@ git fetch --all --tags --prune
 git checkout $CE_BRANCH
 cd ..
 
-
-# get commit hash
-EE_COMMIT=$(git log --oneline | head -1 | cut -d' ' -f1)
-
-# Setup a clean EE environment
-msg "Cleaning the EE directory..."
-rm -rf $ent_dir
-mkdir $ent_dir
-$rsync_bin -a --exclude "/$(basename "$BASE_DIR")" ../* $ent_dir/
-
-
-# load files
-source config
-
-msg "Copying EE files..."
-# remove EE files
-for file in "${encrypted_files[@]}"; do
-		rm -rf ${ent_dir}/$file
-done
-for file in "${enterprise_files[@]}"; do
-	rm -rf ${ent_dir}/$file
-done
-
-# copy community files
-for file in "${community_files[@]}"; do
-	if [ -e "${com_dir}/$file" ]; then
-		cp ${com_dir}/$file ${ent_dir}/$(dirname $file)
-	else
-		echo "The CE file/dir is not found: ${ent_dir}/$file"
-	fi
-done
-
-# keep the CE build-pkg dir
-rm -rf ${ent_dir}/build-pkg
-cp -r ${com_dir}/build-pkg ${ent_dir}
-
-# keep the CE DEBIAN dir
-rm -rf ${ent_dir}/DEBIAN
-cp -r ${com_dir}/DEBIAN ${ent_dir}
-
 # clean the CE to detect if a file has been deleted
 rm -rf ${com_dir}/*
 
 # copy all EE to the CE
-cp -r ${ent_dir}/* $com_dir
+cp -r ${tmp_dir}/* $com_dir
+rm -rf ${tmp_dir}/*
 
 
 # apply the commit to CE
